# Generated by Django 4.2.16 on 2026-08-16 09:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("benchmark", "0001_initial"),
        ("libraries", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MCDMEvaluationRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mcdm_method",
                    models.CharField(
                        choices=[
                            (
                                "TOPSIS",
                                "TOPSIS (Technique for Order Preference by Similarity to Ideal Solution)",
                            ),
                            ("WSM", "WSM (Weighted Sum Model)"),
                            ("WPM", "WPM (Weighted Product Model)"),
                            ("AHP", "AHP (Analytic Hierarchy Process)"),
                            ("HYBRID", "Hybrid (AHP Weights + TOPSIS Distance)"),
                        ],
                        default="TOPSIS",
                        max_length=30,
                    ),
                ),
                ("candidate_count", models.PositiveIntegerField(default=0)),
                (
                    "decision_matrix_json",
                    models.JSONField(
                        default=dict, help_text="Raw unnormalized decision matrix"
                    ),
                ),
                (
                    "normalized_matrix_json",
                    models.JSONField(
                        default=dict, help_text="Normalized decision matrix"
                    ),
                ),
                (
                    "ranking_results_json",
                    models.JSONField(
                        default=list, help_text="Ordered ranking output with scores"
                    ),
                ),
                (
                    "benchmark_task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mcdm_evaluations",
                        to="benchmark.benchmarktask",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mcdm_evaluations",
                        to="libraries.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "MCDM Evaluation Run",
                "verbose_name_plural": "MCDM Evaluation Runs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MCDMWeightProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("profile_name", models.CharField(max_length=100, unique=True)),
                (
                    "profile_type",
                    models.CharField(
                        choices=[
                            ("BALANCED", "Balanced Decision Profile"),
                            ("ENERGY_FOCUSED", "Energy-First Profile"),
                            ("PERFORMANCE_FOCUSED", "Low-Latency Performance Profile"),
                            ("MEMORY_FOCUSED", "Memory-Constrained Profile"),
                            ("CARBON_NEUTRAL", "Minimal Carbon Emissions Profile"),
                            ("CUSTOM", "Custom Stakeholder Defined Profile"),
                        ],
                        default="BALANCED",
                        max_length=30,
                    ),
                ),
                (
                    "weight_energy",
                    models.FloatField(
                        default=0.35,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "weight_execution_time",
                    models.FloatField(
                        default=0.25,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "weight_cpu",
                    models.FloatField(
                        default=0.15,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "weight_memory",
                    models.FloatField(
                        default=0.15,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "weight_co2",
                    models.FloatField(
                        default=0.1,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "MCDM Weight Profile",
                "verbose_name_plural": "MCDM Weight Profiles",
                "ordering": ["profile_name"],
            },
        ),
        migrations.CreateModel(
            name="SensitivityAuditReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("perturbed_criterion", models.CharField(max_length=50)),
                (
                    "perturbation_pct",
                    models.FloatField(
                        help_text="Percentage change in criterion weight (+/- %)"
                    ),
                ),
                ("rank_reversals_count", models.PositiveIntegerField(default=0)),
                (
                    "spearman_rho",
                    models.FloatField(
                        default=1.0, help_text="Spearman's rank correlation coefficient"
                    ),
                ),
                ("is_robust", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "evaluation_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sensitivity_reports",
                        to="mcdm.mcdmevaluationrun",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sensitivity Audit Report",
                "verbose_name_plural": "Sensitivity Audit Reports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="mcdmevaluationrun",
            name="weight_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evaluation_runs",
                to="mcdm.mcdmweightprofile",
            ),
        ),
        migrations.CreateModel(
            name="GreenScoreRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "green_score",
                    models.FloatField(
                        help_text="Calibrated 0-100 score",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                    ),
                ),
                (
                    "rank_position",
                    models.PositiveIntegerField(
                        help_text="Relative rank position (1 is best)"
                    ),
                ),
                (
                    "closeness_coefficient",
                    models.FloatField(
                        default=0.0,
                        help_text="TOPSIS Relative Closeness C_i* (0.0 - 1.0)",
                    ),
                ),
                ("wsm_score", models.FloatField(default=0.0)),
                ("wpm_score", models.FloatField(default=0.0)),
                (
                    "confidence_score",
                    models.FloatField(
                        default=95.0,
                        help_text="Confidence index based on sample consistency",
                    ),
                ),
                (
                    "explanation_text",
                    models.TextField(
                        help_text="Explainable AI narrative justification"
                    ),
                ),
                (
                    "evaluation_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="green_score_records",
                        to="mcdm.mcdmevaluationrun",
                    ),
                ),
                (
                    "library",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mcdm_green_scores",
                        to="libraries.library",
                    ),
                ),
            ],
            options={
                "verbose_name": "Green Score Record",
                "verbose_name_plural": "Green Score Records",
                "ordering": ["rank_position"],
            },
        ),
        migrations.CreateModel(
            name="AHPComparisonMatrix",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "matrix_json",
                    models.JSONField(
                        default=dict, help_text="5x5 Pairwise comparison matrix"
                    ),
                ),
                ("consistency_index", models.FloatField(default=0.0)),
                (
                    "consistency_ratio",
                    models.FloatField(
                        default=0.0, help_text="CR = CI / RI (Must be < 0.10)"
                    ),
                ),
                ("is_consistent", models.BooleanField(default=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ahp_matrices",
                        to="mcdm.mcdmweightprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "AHP Comparison Matrix",
                "verbose_name_plural": "AHP Comparison Matrices",
            },
        ),
    ]
