# Generated by Django 4.2.16 on 2026-08-16 09:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("libraries", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarbonImpactReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("total_libraries_audited", models.PositiveIntegerField(default=0)),
                ("total_energy_kwh", models.FloatField(default=0.0)),
                ("total_carbon_kg", models.FloatField(default=0.0)),
                ("baseline_savings_potential_kg", models.FloatField(default=0.0)),
                ("summary_metrics", models.JSONField(default=dict)),
            ],
            options={
                "verbose_name": "Carbon Impact Report",
                "verbose_name_plural": "Carbon Impact Reports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RegionalGridCarbonFactor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "region_code",
                    models.CharField(
                        help_text="e.g. us-east-1, eu-west-1, in-west-1",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("region_name", models.CharField(max_length=150)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("AWS", "Amazon Web Services"),
                            ("GCP", "Google Cloud Platform"),
                            ("AZURE", "Microsoft Azure"),
                            ("NATIONAL_GRID", "National Public Electrical Grid"),
                            ("ON_PREMISE", "On-Premise Private Datacenter"),
                        ],
                        default="AWS",
                        max_length=30,
                    ),
                ),
                ("country", models.CharField(max_length=100)),
                (
                    "carbon_intensity_g_per_kwh",
                    models.FloatField(
                        help_text="Grid carbon intensity in gCO2e per kWh (e.g. 385.0)"
                    ),
                ),
                (
                    "pue_factor",
                    models.FloatField(
                        default=1.15,
                        help_text="Power Usage Effectiveness (PUE)",
                        validators=[
                            django.core.validators.MinValueValidator(1.0),
                            django.core.validators.MaxValueValidator(3.0),
                        ],
                    ),
                ),
                (
                    "renewable_share_pct",
                    models.FloatField(
                        default=25.0,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Regional Grid Carbon Factor",
                "verbose_name_plural": "Regional Grid Carbon Factors",
                "ordering": ["region_code"],
            },
        ),
        migrations.CreateModel(
            name="CarbonSavingsEstimate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "requests_per_year",
                    models.BigIntegerField(
                        default=10000000, help_text="Annual execution traffic volume"
                    ),
                ),
                (
                    "energy_saved_kwh",
                    models.FloatField(help_text="Annual energy saved in kWh"),
                ),
                (
                    "carbon_saved_kg",
                    models.FloatField(help_text="Annual CO2e avoided in kg"),
                ),
                (
                    "carbon_reduction_pct",
                    models.FloatField(help_text="Percentage reduction in emissions"),
                ),
                (
                    "trees_equivalent",
                    models.FloatField(
                        help_text="Equivalent urban tree seedlings grown for 10 years"
                    ),
                ),
                (
                    "vehicle_km_avoided",
                    models.FloatField(
                        help_text="Equivalent passenger vehicle kilometers avoided"
                    ),
                ),
                (
                    "cost_saved_usd",
                    models.FloatField(
                        help_text="Estimated electricity cost saved in USD ($0.14/kWh)"
                    ),
                ),
                (
                    "explanation_narrative",
                    models.TextField(
                        help_text="Explainable sustainability justification"
                    ),
                ),
                (
                    "regional_grid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="savings_estimates",
                        to="carbon.regionalgridcarbonfactor",
                    ),
                ),
                (
                    "source_library",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="savings_as_source",
                        to="libraries.library",
                    ),
                ),
                (
                    "target_library",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="savings_as_target",
                        to="libraries.library",
                    ),
                ),
            ],
            options={
                "verbose_name": "Carbon Savings Estimate",
                "verbose_name_plural": "Carbon Savings Estimates",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CarbonForecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("forecast_horizon_months", models.PositiveIntegerField(default=12)),
                (
                    "projected_monthly_emissions_kg",
                    models.JSONField(
                        default=list,
                        help_text="12-month array of projected monthly emissions",
                    ),
                ),
                ("trend_slope", models.FloatField(default=0.0)),
                ("confidence_interval", models.FloatField(default=95.0)),
                (
                    "library",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carbon_forecasts",
                        to="libraries.library",
                    ),
                ),
                (
                    "regional_grid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forecasts",
                        to="carbon.regionalgridcarbonfactor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Carbon Forecast",
                "verbose_name_plural": "Carbon Forecasts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CarbonEmissionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("energy_joules", models.FloatField()),
                ("energy_kwh", models.FloatField()),
                (
                    "carbon_emissions_g",
                    models.FloatField(
                        help_text="Direct carbon emissions in grams CO2e"
                    ),
                ),
                (
                    "carbon_emissions_kg",
                    models.FloatField(help_text="Carbon emissions in kilograms CO2e"),
                ),
                (
                    "annualized_emissions_kg",
                    models.FloatField(
                        default=0.0,
                        help_text="Projected annual emissions at 10M requests",
                    ),
                ),
                (
                    "carbon_score",
                    models.FloatField(
                        default=85.0, help_text="Carbon efficiency score (0-100)"
                    ),
                ),
                ("confidence_score", models.FloatField(default=95.0)),
                (
                    "library",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carbon_records",
                        to="libraries.library",
                    ),
                ),
                (
                    "regional_grid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emission_records",
                        to="carbon.regionalgridcarbonfactor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Carbon Emission Record",
                "verbose_name_plural": "Carbon Emission Records",
                "ordering": ["-created_at"],
            },
        ),
    ]
