# Generated by Django 4.2.16 on 2026-07-26 11:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("description", models.TextField()),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Bootstrap or FontAwesome icon class",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Functional Category",
                "verbose_name_plural": "Functional Categories",
                "ordering": ["category_name"],
            },
        ),
        migrations.CreateModel(
            name="ProgrammingLanguage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language_name", models.CharField(max_length=50, unique=True)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="languages/logos/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Programming Language",
                "verbose_name_plural": "Programming Languages",
                "ordering": ["language_name"],
            },
        ),
        migrations.CreateModel(
            name="Library",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("library_name", models.CharField(db_index=True, max_length=100)),
                ("official_name", models.CharField(max_length=150)),
                ("description", models.TextField()),
                ("package_manager", models.CharField(default="PyPI", max_length=50)),
                (
                    "repository_url",
                    models.URLField(
                        blank=True, validators=[django.core.validators.URLValidator()]
                    ),
                ),
                (
                    "documentation_url",
                    models.URLField(
                        blank=True, validators=[django.core.validators.URLValidator()]
                    ),
                ),
                (
                    "homepage_url",
                    models.URLField(
                        blank=True, validators=[django.core.validators.URLValidator()]
                    ),
                ),
                (
                    "current_version",
                    models.CharField(
                        help_text="Latest stable version pin", max_length=30
                    ),
                ),
                ("license", models.CharField(default="MIT", max_length=50)),
                ("maintainer", models.CharField(blank=True, max_length=100)),
                (
                    "popularity_score",
                    models.IntegerField(
                        default=0, help_text="GitHub Stars / PyPI Rating"
                    ),
                ),
                (
                    "downloads",
                    models.BigIntegerField(
                        default=0, help_text="Monthly download statistics"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="libraries",
                        to="libraries.category",
                    ),
                ),
                (
                    "programming_language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="libraries",
                        to="libraries.programminglanguage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Software Library",
                "verbose_name_plural": "Software Libraries",
                "ordering": ["library_name"],
            },
        ),
        migrations.CreateModel(
            name="SimilarLibraryMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "similarity_type",
                    models.CharField(
                        choices=[
                            ("DIRECT", "Direct Drop-in Replacement"),
                            (
                                "FUNCTIONAL",
                                "Functional Equivalent (Minor API differences)",
                            ),
                            ("PARADIGM", "Paradigm Alternative (Async / C-Extension)"),
                        ],
                        default="FUNCTIONAL",
                        max_length=30,
                    ),
                ),
                (
                    "similarity_score",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="API Compatibility Score (0.00 to 1.00)",
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        help_text="Explanation of functional equivalence or minor API differences"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "source_library",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_mappings",
                        to="libraries.library",
                    ),
                ),
                (
                    "target_library",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="target_mappings",
                        to="libraries.library",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Similar Library Mapping",
                "verbose_name_plural": "Similar Library Mappings",
                "unique_together": {("source_library", "target_library")},
            },
        ),
        migrations.CreateModel(
            name="LibraryVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version_number", models.CharField(max_length=30)),
                ("release_date", models.DateField(blank=True, null=True)),
                ("release_notes", models.TextField(blank=True)),
                (
                    "supported_python_version",
                    models.CharField(default=">=3.8", max_length=50),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "library",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="libraries.library",
                    ),
                ),
            ],
            options={
                "verbose_name": "Library Version",
                "verbose_name_plural": "Library Versions",
                "ordering": ["-release_date", "-version_number"],
                "unique_together": {("library", "version_number")},
            },
        ),
        migrations.AddIndex(
            model_name="library",
            index=models.Index(
                fields=["library_name", "category"],
                name="libraries_l_library_3f3727_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="library",
            unique_together={("library_name", "programming_language")},
        ),
    ]
