# Generated by Django 4.2.16 on 2026-08-16 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libraries", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="library",
            name="current_version",
            field=models.CharField(
                blank=True,
                default="1.0.0",
                help_text="Latest stable version pin",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="library",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="library",
            name="downloads",
            field=models.BigIntegerField(
                blank=True, default=0, help_text="Monthly download statistics"
            ),
        ),
        migrations.AlterField(
            model_name="library",
            name="license",
            field=models.CharField(blank=True, default="MIT", max_length=50),
        ),
        migrations.AlterField(
            model_name="library",
            name="official_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="library",
            name="package_manager",
            field=models.CharField(blank=True, default="PyPI", max_length=50),
        ),
        migrations.AlterField(
            model_name="library",
            name="popularity_score",
            field=models.IntegerField(
                blank=True, default=0, help_text="GitHub Stars / PyPI Rating"
            ),
        ),
        migrations.AlterField(
            model_name="library",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ACTIVE", "Active"),
                    ("INACTIVE", "Inactive"),
                    ("ARCHIVED", "Archived"),
                ],
                default="ACTIVE",
                max_length=20,
            ),
        ),
    ]
