# Generated by Django 4.2.16 on 2026-08-16 10:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libraries", "0002_alter_library_current_version_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="similarlibrarymapping",
            name="reason",
            field=models.TextField(
                blank=True,
                help_text="Explanation of functional equivalence or minor API differences",
            ),
        ),
        migrations.AlterField(
            model_name="similarlibrarymapping",
            name="similarity_score",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0.85,
                help_text="API Compatibility Score (0.00 to 1.00)",
                max_digits=4,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="similarlibrarymapping",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ACTIVE", "Active"),
                    ("INACTIVE", "Inactive"),
                    ("ARCHIVED", "Archived"),
                ],
                default="ACTIVE",
                max_length=20,
            ),
        ),
    ]
