# Generated by Django 4.2.16 on 2026-07-26 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("benchmark", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("libraries", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeightProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("profile_name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField()),
                ("is_default", models.BooleanField(default=False)),
                (
                    "weight_execution_time",
                    models.DecimalField(decimal_places=4, default=0.3, max_digits=5),
                ),
                (
                    "weight_cpu_usage",
                    models.DecimalField(decimal_places=4, default=0.2, max_digits=5),
                ),
                (
                    "weight_peak_memory",
                    models.DecimalField(decimal_places=4, default=0.2, max_digits=5),
                ),
                (
                    "weight_energy",
                    models.DecimalField(decimal_places=4, default=0.2, max_digits=5),
                ),
                (
                    "weight_co2",
                    models.DecimalField(decimal_places=4, default=0.1, max_digits=5),
                ),
            ],
            options={
                "verbose_name": "Weight Profile",
                "verbose_name_plural": "Weight Profiles",
                "ordering": ["profile_name"],
            },
        ),
        migrations.CreateModel(
            name="RecommendationRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recommendation_profile",
                    models.CharField(
                        choices=[
                            ("BEST_OVERALL", "Best Overall Green Score"),
                            (
                                "MOST_ENERGY_EFFICIENT",
                                "Most Energy Efficient (Lowest Joules)",
                            ),
                            ("FASTEST", "Fastest Execution (Lowest Latency)"),
                            ("LOWEST_MEMORY", "Lowest Memory Footprint (Lowest RAM)"),
                            ("LOWEST_CPU", "Lowest CPU Utilization"),
                            ("LOWEST_CO2", "Lowest Carbon Footprint (Lowest gCO2eq)"),
                        ],
                        default="BEST_OVERALL",
                        max_length=30,
                    ),
                ),
                ("candidates_evaluated_count", models.IntegerField(default=0)),
                (
                    "target_library",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendation_queries",
                        to="libraries.library",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="benchmark.benchmarktask",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Recommendation Record",
                "verbose_name_plural": "Recommendation Records",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RecommendationItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("rank", models.IntegerField()),
                ("green_score", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "confidence_score",
                    models.DecimalField(decimal_places=3, max_digits=4),
                ),
                ("explanation_text", models.TextField()),
                ("is_top_choice", models.BooleanField(default=False)),
                (
                    "recommended_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommended_in_items",
                        to="libraries.libraryversion",
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="recommendation.recommendationrecord",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recommendation Item",
                "verbose_name_plural": "Recommendation Items",
                "ordering": ["rank"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalGreenScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("score", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "strategy_used",
                    models.CharField(
                        choices=[
                            ("WSM", "Weighted Sum Model (WSM)"),
                            ("WPM", "Weighted Product Model (WPM)"),
                            ("TOPSIS", "TOPSIS (Ideal Solution Distance)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "library_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historical_scores",
                        to="libraries.libraryversion",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historical_scores",
                        to="benchmark.benchmarktask",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historical Green Score",
                "verbose_name_plural": "Historical Green Scores",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GreenScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "strategy_used",
                    models.CharField(
                        choices=[
                            ("WSM", "Weighted Sum Model (WSM)"),
                            ("WPM", "Weighted Product Model (WPM)"),
                            ("TOPSIS", "TOPSIS (Ideal Solution Distance)"),
                        ],
                        default="TOPSIS",
                        max_length=20,
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Green Score on a 0.00 - 100.00 scale",
                        max_digits=6,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("EXCELLENT", "Excellent (90-100)"),
                            ("GOOD", "Good (70-89)"),
                            ("AVERAGE", "Average (50-69)"),
                            ("NEEDS_IMPROVEMENT", "Needs Improvement (<50)"),
                        ],
                        default="GOOD",
                        max_length=20,
                    ),
                ),
                (
                    "confidence_score",
                    models.DecimalField(
                        decimal_places=3,
                        default=0.95,
                        help_text="Statistical confidence score (0.000 - 1.000)",
                        max_digits=4,
                    ),
                ),
                (
                    "explanation",
                    models.TextField(help_text="Human-readable score explanation text"),
                ),
                (
                    "library_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="green_scores",
                        to="libraries.libraryversion",
                    ),
                ),
                (
                    "result",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="green_score_record",
                        to="benchmark.benchmarkresult",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="green_scores",
                        to="benchmark.benchmarksession",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="green_scores",
                        to="benchmark.benchmarktask",
                    ),
                ),
                (
                    "weight_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="green_scores",
                        to="recommendation.weightprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Green Score",
                "verbose_name_plural": "Green Scores",
                "ordering": ["-score"],
                "indexes": [
                    models.Index(fields=["score"], name="recommendat_score_722281_idx"),
                    models.Index(
                        fields=["library_version", "task"],
                        name="recommendat_library_e14673_idx",
                    ),
                ],
            },
        ),
    ]
