# Generated by Django 4.2.16 on 2026-08-16 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("libraries", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIPredictionModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("model_name", models.CharField(max_length=150)),
                ("version", models.CharField(default="1.0.0", max_length=20)),
                (
                    "algorithm",
                    models.CharField(
                        choices=[
                            ("RIDGE_REGRESSION", "L2-Regularized Ridge Regression"),
                            ("RANDOM_FOREST", "Ensemble Random Forest Regressor"),
                            ("GRADIENT_BOOSTING", "Gradient Boosted Decision Trees"),
                            ("LINEAR_REGRESSION", "Ordinary Least Squares Regression"),
                        ],
                        default="RIDGE_REGRESSION",
                        max_length=30,
                    ),
                ),
                (
                    "target_metric",
                    models.CharField(
                        choices=[
                            ("GREEN_SCORE", "Multi-Criteria Green Score (0-100)"),
                            ("ENERGY_JOULES", "Package Energy Consumption (Joules)"),
                            ("EXECUTION_TIME_MS", "Execution Latency (Milliseconds)"),
                            ("RAM_RSS_MB", "RAM Resident Set Size (MB)"),
                            ("CPU_UTILIZATION_PCT", "CPU Utilization (%)"),
                        ],
                        default="GREEN_SCORE",
                        max_length=30,
                    ),
                ),
                (
                    "r2_score",
                    models.FloatField(
                        default=0.0, help_text="Coefficient of Determination R^2"
                    ),
                ),
                (
                    "rmse",
                    models.FloatField(default=0.0, help_text="Root Mean Squared Error"),
                ),
                (
                    "mae",
                    models.FloatField(default=0.0, help_text="Mean Absolute Error"),
                ),
                (
                    "mape",
                    models.FloatField(
                        default=0.0, help_text="Mean Absolute Percentage Error (%)"
                    ),
                ),
                (
                    "feature_names",
                    models.JSONField(
                        default=list, help_text="Ordered list of feature column names"
                    ),
                ),
                (
                    "feature_weights",
                    models.JSONField(
                        default=dict,
                        help_text="Feature importance weights or linear coefficients",
                    ),
                ),
                (
                    "model_parameters",
                    models.JSONField(
                        default=dict,
                        help_text="Trained model coefficients/hyperparameters",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Active model for online inference"
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Prediction Model",
                "verbose_name_plural": "AI Prediction Models",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SustainabilityPrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "target_metric",
                    models.CharField(
                        choices=[
                            ("GREEN_SCORE", "Multi-Criteria Green Score (0-100)"),
                            ("ENERGY_JOULES", "Package Energy Consumption (Joules)"),
                            ("EXECUTION_TIME_MS", "Execution Latency (Milliseconds)"),
                            ("RAM_RSS_MB", "RAM Resident Set Size (MB)"),
                            ("CPU_UTILIZATION_PCT", "CPU Utilization (%)"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "predicted_value",
                    models.FloatField(help_text="Predicted numerical metric value"),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        default=0.0, help_text="Prediction confidence index (0-100%)"
                    ),
                ),
                (
                    "explanation_text",
                    models.TextField(
                        help_text="Human-readable explanation of why this prediction was made"
                    ),
                ),
                (
                    "feature_attribution",
                    models.JSONField(
                        default=dict,
                        help_text="SHAP-style relative feature contributions",
                    ),
                ),
                (
                    "actual_measured_value",
                    models.FloatField(
                        blank=True,
                        help_text="Actual physical measurement if later benchmarked",
                        null=True,
                    ),
                ),
                (
                    "prediction_error_pct",
                    models.FloatField(
                        blank=True,
                        help_text="Absolute percentage error |Pred - Actual| / Actual",
                        null=True,
                    ),
                ),
                (
                    "library",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_predictions",
                        to="libraries.library",
                    ),
                ),
                (
                    "model_used",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="predictions",
                        to="ai.aipredictionmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sustainability Prediction",
                "verbose_name_plural": "Sustainability Predictions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ModelTrainingRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("training_sample_size", models.PositiveIntegerField()),
                ("test_sample_size", models.PositiveIntegerField()),
                ("duration_seconds", models.FloatField(default=0.0)),
                ("train_r2", models.FloatField(default=0.0)),
                ("val_r2", models.FloatField(default=0.0)),
                ("hyperparameters", models.JSONField(default=dict)),
                ("training_log", models.TextField(blank=True)),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_runs",
                        to="ai.aipredictionmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Model Training Run",
                "verbose_name_plural": "Model Training Runs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FeatureRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("lines_of_code", models.PositiveIntegerField(default=10000)),
                ("dependency_count", models.PositiveIntegerField(default=2)),
                ("popularity_score", models.PositiveIntegerField(default=100)),
                ("category_id_val", models.IntegerField(default=1)),
                ("language_id_val", models.IntegerField(default=1)),
                (
                    "feature_vector",
                    models.JSONField(
                        default=dict, help_text="Normalized numerical feature array"
                    ),
                ),
                (
                    "library",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature_record",
                        to="libraries.library",
                    ),
                ),
            ],
            options={
                "verbose_name": "Feature Record",
                "verbose_name_plural": "Feature Records",
            },
        ),
        migrations.CreateModel(
            name="DriftReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("total_evaluated_samples", models.PositiveIntegerField()),
                (
                    "mean_prediction_error_pct",
                    models.FloatField(
                        help_text="Mean absolute percentage error across evaluated predictions"
                    ),
                ),
                (
                    "feature_drift_score",
                    models.FloatField(
                        default=0.0,
                        help_text="Wasserstein / KS feature drift distance (0-1.0)",
                    ),
                ),
                ("drift_detected", models.BooleanField(default=False)),
                ("recommendation_notes", models.TextField()),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drift_reports",
                        to="ai.aipredictionmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Model Drift Report",
                "verbose_name_plural": "Model Drift Reports",
                "ordering": ["-created_at"],
            },
        ),
    ]
