# Generated by Django 4.2.16 on 2026-08-16 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("libraries", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GraphSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.CharField(default="1.0.0", max_length=20)),
                ("node_count", models.PositiveIntegerField(default=0)),
                ("edge_count", models.PositiveIntegerField(default=0)),
                ("graph_density", models.FloatField(default=0.0)),
                ("checksum_sha256", models.CharField(blank=True, max_length=64)),
                ("summary_metrics", models.JSONField(default=dict)),
            ],
            options={
                "verbose_name": "Graph Snapshot",
                "verbose_name_plural": "Graph Snapshots",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LibraryEmbedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("embedding_type", models.CharField(default="TF_IDF", max_length=30)),
                (
                    "vector_json",
                    models.JSONField(
                        default=dict, help_text="Sparse or dense term weight vector"
                    ),
                ),
                ("dimension", models.PositiveIntegerField(default=0)),
                (
                    "library",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embedding",
                        to="libraries.library",
                    ),
                ),
            ],
            options={
                "verbose_name": "Library Embedding",
                "verbose_name_plural": "Library Embeddings",
            },
        ),
        migrations.CreateModel(
            name="KnowledgeGraphNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "node_type",
                    models.CharField(
                        choices=[
                            ("LIBRARY", "Software Library Node"),
                            ("CATEGORY", "Functional Task Category Node"),
                            ("LANGUAGE", "Programming Language Node"),
                            ("BENCHMARK_TASK", "Benchmark Workload Task Node"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "entity_id",
                    models.PositiveIntegerField(
                        help_text="Primary key of source entity (e.g. Library.id)"
                    ),
                ),
                ("label", models.CharField(db_index=True, max_length=150)),
                (
                    "properties_json",
                    models.JSONField(
                        default=dict, help_text="Node metadata and attributes"
                    ),
                ),
                ("in_degree", models.PositiveIntegerField(default=0)),
                ("out_degree", models.PositiveIntegerField(default=0)),
                (
                    "pagerank_score",
                    models.FloatField(
                        default=1.0, help_text="Calculated PageRank centrality score"
                    ),
                ),
            ],
            options={
                "verbose_name": "Knowledge Graph Node",
                "verbose_name_plural": "Knowledge Graph Nodes",
                "ordering": ["label"],
                "unique_together": {("node_type", "entity_id")},
            },
        ),
        migrations.CreateModel(
            name="KnowledgeGraphEdge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            (
                                "DIRECT_REPLACEMENT",
                                "Direct Drop-in Replacement (API Compatible)",
                            ),
                            ("FUNCTIONAL_ALTERNATIVE", "Functional Alternative"),
                            ("COMPETES_WITH", "Competes With (Same Domain)"),
                            ("BELONGS_TO", "Belongs to Category"),
                            ("IMPLEMENTS_LANGUAGE", "Written in Language"),
                            ("DEPENDS_ON", "Direct Software Dependency"),
                            ("EXTENDS", "Extends / Wraps Library"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "weight",
                    models.FloatField(
                        default=1.0,
                        help_text="Edge weight (e.g. similarity score or energy differential)",
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        default=100.0, help_text="Relationship confidence (0-100%)"
                    ),
                ),
                ("metadata_json", models.JSONField(blank=True, default=dict)),
                (
                    "source_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_edges",
                        to="knowledge_graph.knowledgegraphnode",
                    ),
                ),
                (
                    "target_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_edges",
                        to="knowledge_graph.knowledgegraphnode",
                    ),
                ),
            ],
            options={
                "verbose_name": "Knowledge Graph Edge",
                "verbose_name_plural": "Knowledge Graph Edges",
                "ordering": ["-weight"],
            },
        ),
        migrations.CreateModel(
            name="SimilarityScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("cosine_similarity", models.FloatField(default=0.0)),
                ("jaccard_similarity", models.FloatField(default=0.0)),
                (
                    "composite_similarity",
                    models.FloatField(
                        default=0.0,
                        help_text="Hybrid composite similarity score (0.0 - 1.0)",
                    ),
                ),
                (
                    "is_discovered",
                    models.BooleanField(
                        default=True,
                        help_text="Automatically discovered by NLP pipeline",
                    ),
                ),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            (
                                "DIRECT_REPLACEMENT",
                                "Direct Drop-in Replacement (API Compatible)",
                            ),
                            ("FUNCTIONAL_ALTERNATIVE", "Functional Alternative"),
                            ("COMPETES_WITH", "Competes With (Same Domain)"),
                            ("BELONGS_TO", "Belongs to Category"),
                            ("IMPLEMENTS_LANGUAGE", "Written in Language"),
                            ("DEPENDS_ON", "Direct Software Dependency"),
                            ("EXTENDS", "Extends / Wraps Library"),
                        ],
                        default="FUNCTIONAL_ALTERNATIVE",
                        max_length=40,
                    ),
                ),
                (
                    "source_library",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_similarities",
                        to="libraries.library",
                    ),
                ),
                (
                    "target_library",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="target_similarities",
                        to="libraries.library",
                    ),
                ),
            ],
            options={
                "verbose_name": "Similarity Score",
                "verbose_name_plural": "Similarity Scores",
                "ordering": ["-composite_similarity"],
                "unique_together": {("source_library", "target_library")},
            },
        ),
    ]
