# Generated by Django 4.2.16 on 2026-07-26 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneratedReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("report_name", models.CharField(max_length=200)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("CATEGORY", "Category Summary Report"),
                            ("COMPARISON", "Side-by-Side Comparison Report"),
                            ("DATASET", "Full EcoLibBench Dataset Export"),
                        ],
                        default="CATEGORY",
                        max_length=30,
                    ),
                ),
                ("generated_on", models.DateTimeField(auto_now_add=True)),
                (
                    "pdf_file",
                    models.FileField(blank=True, null=True, upload_to="reports/pdf/"),
                ),
                (
                    "csv_file",
                    models.FileField(blank=True, null=True, upload_to="reports/csv/"),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "generated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Generated Report",
                "verbose_name_plural": "Generated Reports",
                "ordering": ["-generated_on"],
            },
        ),
    ]
