# Generated by Django 4.2.16 on 2026-08-16 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libraries", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademicReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                (
                    "publication_format",
                    models.CharField(
                        choices=[
                            (
                                "MCA_DISSERTATION",
                                "MCA Research Master Dissertation (Chapters 1-8)",
                            ),
                            (
                                "IEEE_CONFERENCE",
                                "IEEE Conference Paper (Two-Column IEEEtran)",
                            ),
                            (
                                "ACM_CONFERENCE",
                                "ACM Conference Proceedings (ACM sigconf)",
                            ),
                            (
                                "TECHNICAL_REPORT",
                                "Technical Benchmark & Evaluation Report",
                            ),
                            (
                                "BENCHMARK_REPORT",
                                "Empirical Telemetry Performance Audit",
                            ),
                            ("OPEN_SCIENCE_BUNDLE", "Open Science Replication Package"),
                        ],
                        default="IEEE_CONFERENCE",
                        max_length=30,
                    ),
                ),
                (
                    "author_name",
                    models.CharField(
                        default="Vikash Kumar & Research Team", max_length=150
                    ),
                ),
                (
                    "affiliation",
                    models.CharField(
                        default="Department of Computer Science & Engineering",
                        max_length=200,
                    ),
                ),
                ("abstract", models.TextField()),
                (
                    "keywords",
                    models.CharField(
                        default="Green Software Engineering, Energy Benchmarking, Carbon Intensity, MCDM, TOPSIS, EcoDep",
                        max_length=255,
                    ),
                ),
                (
                    "content_markdown",
                    models.TextField(help_text="Renderable Markdown manuscript"),
                ),
                (
                    "content_latex",
                    models.TextField(help_text="Publication-ready LaTeX source code"),
                ),
                (
                    "bibliography_bibtex",
                    models.TextField(help_text="BibTeX reference entries"),
                ),
                ("is_published", models.BooleanField(default=False)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="academic_reports",
                        to="libraries.category",
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Academic Report & Publication",
                "verbose_name_plural": "Academic Reports & Publications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterField(
            model_name="generatedreport",
            name="generated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="generatedreport",
            name="type",
            field=models.CharField(default="CATEGORY", max_length=30),
        ),
        migrations.CreateModel(
            name="ResearchArtifactPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                (
                    "package_type",
                    models.CharField(default="FULL_REPLICATION_PACKAGE", max_length=50),
                ),
                ("archive_manifest_json", models.JSONField(default=dict)),
                ("sha256_checksum", models.CharField(max_length=64)),
                ("replication_instructions", models.TextField()),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artifact_packages",
                        to="reports.academicreport",
                    ),
                ),
            ],
            options={
                "verbose_name": "Research Artifact Package",
                "verbose_name_plural": "Research Artifact Packages",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("section_number", models.CharField(default="1.0", max_length=20)),
                ("section_title", models.CharField(max_length=200)),
                ("section_type", models.CharField(default="BODY", max_length=50)),
                ("body_text", models.TextField()),
                ("table_latex", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=1)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="reports.academicreport",
                    ),
                ),
            ],
            options={
                "verbose_name": "Report Section",
                "verbose_name_plural": "Report Sections",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="PublicationChecklist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("meets_ieee_standards", models.BooleanField(default=True)),
                ("double_blind_ready", models.BooleanField(default=True)),
                ("artifacts_verified", models.BooleanField(default=True)),
                ("reproducibility_score", models.FloatField(default=98.5)),
                ("notes", models.TextField(blank=True)),
                (
                    "report",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checklist",
                        to="reports.academicreport",
                    ),
                ),
            ],
            options={
                "verbose_name": "Publication Checklist",
                "verbose_name_plural": "Publication Checklists",
            },
        ),
    ]
