# Generated by Django 4.2.16 on 2026-08-16 09:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("libraries", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrustScoreRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "overall_trust_score",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ]
                    ),
                ),
                ("data_completeness_score", models.FloatField(default=95.0)),
                ("measurement_fidelity_score", models.FloatField(default=98.0)),
                ("explanation_clarity_score", models.FloatField(default=92.0)),
                (
                    "status_badge",
                    models.CharField(default="High Trust (Verified)", max_length=30),
                ),
                (
                    "library",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trust_scores",
                        to="libraries.library",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trust Score Record",
                "verbose_name_plural": "Trust Score Records",
                "ordering": ["-overall_trust_score"],
            },
        ),
        migrations.CreateModel(
            name="SHAPAttributionResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "base_value",
                    models.FloatField(
                        default=50.0, help_text="Expected baseline Green Score"
                    ),
                ),
                (
                    "shap_values_json",
                    models.JSONField(
                        default=dict,
                        help_text="Dictionary of feature SHAP values phi_i",
                    ),
                ),
                ("top_contributing_features", models.JSONField(default=list)),
                (
                    "library",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shap_results",
                        to="libraries.library",
                    ),
                ),
            ],
            options={
                "verbose_name": "SHAP Attribution Result",
                "verbose_name_plural": "SHAP Attribution Results",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RecommendationExplanation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "explanation_type",
                    models.CharField(
                        choices=[
                            (
                                "WHY_RECOMMENDED",
                                "Why Recommended (Positive Justification)",
                            ),
                            (
                                "WHY_NOT_RECOMMENDED",
                                "Why Not Recommended (Contrastive Analysis)",
                            ),
                            ("COMPARATIVE", "Head-to-Head Comparative Trade-off"),
                            ("COUNTERFACTUAL", 'Counterfactual "What-If" Scenario'),
                            (
                                "SHAP_ATTRIBUTION",
                                "SHAP Feature Attribution Decomposition",
                            ),
                            ("DECISION_TRACE", "Full Decision Lineage & Traceability"),
                        ],
                        default="WHY_RECOMMENDED",
                        max_length=30,
                    ),
                ),
                (
                    "persona",
                    models.CharField(
                        choices=[
                            (
                                "DEVELOPER",
                                "Software Developer (Latency & Memory Focus)",
                            ),
                            (
                                "RESEARCHER",
                                "Scientific Researcher (Confidence & p-value Focus)",
                            ),
                            (
                                "ARCHITECT",
                                "Enterprise Architect (Reliability & Trade-offs)",
                            ),
                            (
                                "ESG_MANAGER",
                                "Sustainability / ESG Manager (Carbon & Energy Focus)",
                            ),
                        ],
                        default="DEVELOPER",
                        max_length=30,
                    ),
                ),
                (
                    "summary_text",
                    models.CharField(
                        help_text="One-sentence executive summary", max_length=255
                    ),
                ),
                (
                    "detailed_narrative",
                    models.TextField(
                        help_text="Complete paragraph-length explainable AI rationale"
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        default=95.0,
                        help_text="Explanation fidelity confidence (0-100%)",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="xai_explanations",
                        to="libraries.category",
                    ),
                ),
                (
                    "library",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="xai_explanations",
                        to="libraries.library",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recommendation Explanation",
                "verbose_name_plural": "Recommendation Explanations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FeatureContribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "feature_name",
                    models.CharField(
                        help_text="e.g. energy_joules, execution_time_ms, ram_rss_mb",
                        max_length=50,
                    ),
                ),
                (
                    "raw_value",
                    models.FloatField(help_text="Observed physical metric value"),
                ),
                (
                    "contribution_score",
                    models.FloatField(
                        help_text="Calculated marginal contribution weight"
                    ),
                ),
                (
                    "percentage_impact",
                    models.FloatField(help_text="Relative percentage impact (0-100%)"),
                ),
                (
                    "is_positive",
                    models.BooleanField(
                        default=True,
                        help_text="True if this feature helped the library rank higher",
                    ),
                ),
                (
                    "explanation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature_contributions",
                        to="xai.recommendationexplanation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Feature Contribution",
                "verbose_name_plural": "Feature Contributions",
                "ordering": ["-percentage_impact"],
            },
        ),
        migrations.CreateModel(
            name="DecisionTraceAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("benchmark_runs_count", models.PositiveIntegerField(default=1)),
                ("weight_profile_used", models.CharField(max_length=100)),
                ("mcdm_solver_used", models.CharField(default="TOPSIS", max_length=50)),
                ("carbon_grid_used", models.CharField(max_length=100)),
                (
                    "trace_hash_sha256",
                    models.CharField(
                        help_text="SHA256 integrity fingerprint", max_length=64
                    ),
                ),
                ("lineage_metadata", models.JSONField(default=dict)),
                (
                    "library",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decision_traces",
                        to="libraries.library",
                    ),
                ),
            ],
            options={
                "verbose_name": "Decision Trace Audit",
                "verbose_name_plural": "Decision Trace Audits",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CounterfactualScenario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "hypothetical_condition",
                    models.CharField(
                        help_text="e.g. Reduce CPU consumption by 15%", max_length=255
                    ),
                ),
                (
                    "resulting_rank",
                    models.PositiveIntegerField(
                        help_text="Projected rank position if condition met"
                    ),
                ),
                (
                    "resulting_green_score",
                    models.FloatField(help_text="Projected new Green Score"),
                ),
                ("is_feasible", models.BooleanField(default=True)),
                ("narrative", models.TextField()),
                (
                    "target_library",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="counterfactuals",
                        to="libraries.library",
                    ),
                ),
            ],
            options={
                "verbose_name": "Counterfactual Scenario",
                "verbose_name_plural": "Counterfactual Scenarios",
                "ordering": ["-created_at"],
            },
        ),
    ]
