# Generated by Django 4.2.16 on 2026-07-26 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PluginEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("event_type", models.CharField(max_length=100)),
                ("payload_json", models.TextField(default="{}")),
            ],
            options={
                "verbose_name": "Plugin Event",
                "verbose_name_plural": "Plugin Events",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PluginManifest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("plugin_id", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=150)),
                ("version", models.CharField(default="1.0.0", max_length=20)),
                (
                    "author",
                    models.CharField(default="EcoDep Core Team", max_length=100),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("BENCHMARK_RUNNER", "Benchmark Runner Harness Plugin"),
                            (
                                "MEASUREMENT_SENSOR",
                                "Physical Measurement Sensor Plugin",
                            ),
                            ("ENERGY_PROVIDER", "Energy & Carbon Provider Plugin"),
                            ("GREEN_SCORE_STRATEGY", "Green Score Strategy Plugin"),
                            (
                                "RECOMMENDATION_STRATEGY",
                                "Recommendation Strategy Plugin",
                            ),
                            ("EXPORT_GENERATOR", "Data Exporter Plugin"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "entry_class",
                    models.CharField(
                        help_text="Python import path to entry plugin class",
                        max_length=255,
                    ),
                ),
                ("checksum_sha256", models.CharField(blank=True, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("is_system_plugin", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Plugin Manifest",
                "verbose_name_plural": "Plugin Manifests",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PluginLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("log_level", models.CharField(default="INFO", max_length=20)),
                ("message", models.TextField()),
                ("traceback", models.TextField(blank=True)),
                (
                    "plugin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="plugins.pluginmanifest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plugin Log",
                "verbose_name_plural": "Plugin Logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
